FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /app

COPY ./publish/ /app
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT docker
EXPOSE 8080

ENTRYPOINT ["dotnet", "/app/AFORO255.MS.TEST.Gateway.dll"]