version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bus-service-test
    ports:
    - 5672:5672
    - 15672:15672
    networks:
      - aforo255-test
  
  consul:
    image: consul
    container_name: consul-service-test
    restart: always
    ports:
    - 8500:8500
    networks:
    - aforo255-test
  
  fabio:
    image: fabiolb/fabio
    container_name: balancer-service-test
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul-service-test:8500
    ports:
    - 9998:9998
    - 9999:9999
    networks:
    - aforo255-test
    depends_on:
      - consul
  
  config:
    image: hyness/spring-cloud-config-server
    container_name: config-service-test
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/juancece/mstestconfig.git
    ports:
      -8888:8888
    networks:
      - aforo255-test
  
  mysql:
    image: mysql
    container_name: mysql-database-test
    build:
      context: ./Db/mysql
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3307:3306"
      - "33061:33060"
    environment:
      MYSQL_ROOT_PASSWORD: "Aforo255#2019"
    networks:
      - aforo255-test
  
  postgres:
    image: postgres
    container_name: postgres-database-test
    build:
      context: ./Db/postgres
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Aforo255#2019"
      DB_NAME: "db_invoice"
    networks:
      - aforo255-test
  
  sql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: sql-database-test
    build:
      context: ./Db/sqlsvr
      dockerfile: ./Dockerfile
    restart: always
    ports:
    - "1434:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Aforo255#2019
    networks:
    - aforo255-test
      
  mongo:
    image: mongo
    container_name: mongo-database-test
    build:
      context: ./Db/mongo
      dockerfile: ./Dockerfile
    restart: always
    ports:
    - "27018:27017"
    networks:
      - aforo255-test
  
networks:
  aforo255-test:
    name: aforo255-test