version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bus-service
    ports:
    - 5672:5672
    - 15672:15672
    networks:
      - aforo255-test
  
  mysql:
    image: mysql
    container_name: mysql-database-test
    build:
      context: ./Db/mysql
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3307:3306"
      - "33061:33060"
    environment:
      MYSQL_ROOT_PASSWORD: "Aforo255#2019"
    networks:
      - aforo255-test
  
  postgres:
    image: postgres
    container_name: postgres-database-test
    build:
      context: ./Db/postgres
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Aforo255#2019"
      DB_NAME: "db_invoice"
    networks:
      - aforo255-test
  
  sql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: sql-database-test
    build:
      context: ./Db/sqlsvr
      dockerfile: ./Dockerfile
    restart: always
    ports:
    - "1434:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Aforo255#2019
    networks:
    - aforo255-test
      
  mongo:
    image: mongo
    container_name: mongo-database-test
    build:
      context: ./Db/mongo
      dockerfile: ./Dockerfile
    restart: always
    ports:
    - "27018:27017"
    networks:
      - aforo255-test
  
networks:
  aforo255-test:
    name: aforo255-test